apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-resume-pv-volume
  labels:
    type: hostPath
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
    type: DirectoryOrCreate
