apiVersion: v1
data:
  db-load-script.sql: "-- Database configuration\nCREATE DATABASE IF NOT EXISTS ecomdb;\nCREATE
    USER IF NOT EXISTS 'ecomuser'@'%' IDENTIFIED BY 'ecompassword';\nGRANT ALL PRIVILEGES
    ON ecomdb.* TO 'ecomuser'@'%' IDENTIFIED BY 'ecompassword';\nFLUSH PRIVILEGES;\n\n--
    Load Product Inventory Information\nUSE ecomdb;\n\nCREATE TABLE IF NOT EXISTS
    products (\n    id mediumint(8) unsigned NOT NULL auto_increment,\n    Name varchar(255)
    default NULL,\n    Price varchar(255) default NULL,\n    ImageUrl varchar(255)
    default NULL,\n    PRIMARY KEY (id)\n) AUTO_INCREMENT=1;\n\nINSERT INTO products
    (Name, Price, ImageUrl) VALUES \n    (\"Laptop\", \"100\", \"c-1.png\"),\n    (\"Drone\",
    \"200\", \"c-2.png\"),\n    (\"VR\", \"300\", \"c-3.png\"),\n    (\"Tablet\",
    \"50\", \"c-5.png\"),\n    (\"Watch\", \"90\", \"c-6.png\"),\n    (\"Phone Covers\",
    \"20\", \"c-7.png\"),\n    (\"Phone\", \"80\", \"c-8.png\"),\n    (\"Laptop\",
    \"150\", \"c-4.png\");\n\n"
kind: ConfigMap
metadata:
  name: db-load-script
