name: Publish Docker image to Docker Hub and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: standard-cluster-1 
  GKE_ZONE: europe-north1-a 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kryten6/ecom-web:${{ github.run_number }}
    - name: publish
      run: |
        docker login -u kryten6 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kryten6/ecom-web:${{ github.run_number }}

    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GK_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        # Update image of deployment. My deployment starts with {{ .Release.Name }}-ecomweb as defined in weh website deployment yaml file. We can clean this up rather than hardcoded like below
        kubectl set image deployment/v1-ecomweb ecom-web=kryten6/ecom-web:${{ github.run_number }}
