name: Docker image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kryten6/ecom-web:latest
    - name: publish
      run: |
        docker login -u kryten6 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kryten6/ecom-web:latest

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '$ {{ secrets.SA_EMAIL }}'

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        # Test commands
        kubectl get services -o wide
