name: Docker image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kryten6/ecom-web:latest
    - name: publish
      run: |
        docker login -u kryten6 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kryten6/ecom-web:latest


    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        # Test commands
        kubectl get services -o wide
