name: Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: standard-cluster-1    # TODO: update to cluster name
  GKE_ZONE: europe-north1-a  # TODO: update to cluster zone

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kryten6/ecom-web:latest
    - name: publish
      run: |
        docker login -u kryten6 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kryten6/ecom-web:latest

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GK_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        # Test commands
        kubectl get services -o wide
        helm upgrade v1 ${{ secrets.HELM_CHART_LOCATION }} --set image.repository=kryten6/ecom-web --set image.tag=latest
